#pragma once
enum class FrameBufferName
{
    FRAMEBUFFER2DEARLY,
    DIRECTIONLIGHTSHADOWFRAMEBUFFER,
    MSAABUFFER1,
    MSAABUFFER2,
    MSAABUFFER3,
    BLURFRAMEBUFFER,
    FRAMEGEOMETRICDEBUGER,
    FRAMESKINNEDMESHDEBUG,
    FRAMEBUFFER2DLATE,

    FRAMESAMPLE,
    FRAMEVOLUMENTRICLIGHTSCATTREING,
    FRAMEEFFECTMOTIONBLUR,
    SOFTSHADOWFRAMEBUFFER,
    FRAMEEFFECTBLOOM,

    FRAMESCENEDEBUG,
    MAINBLITFRAMEBUFFER,
    
    
    MSAATEMPFRAMEBUFFER,
    FRAMEEFFECTSUPPORT1,
    FRAMEEFFECTSUPPORT2,
    FRAMEEFFECTSUPPORT3, 
    FRAMEEFFECTSUPPORT4,
    FRAMEEFFECTSUPPORT5,
    FRAMEDUMMYSUPPORT,
    TESTBUFER,
    FRAMETHUMBNAIL,

    POINTLIGHTSSHADOWMAP,

    NON
};